[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7272dc2c37aa76c29fbf29f5644d162f4b70bd78"
libc = "glibc"
os = "linux"

    [[scopehal.download]]
    sha256 = "3b60c2922a20dc6f57c8fe8509b2544c9c3eb2dfd6261e4411f0f0eb82e39929"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.i686-linux-gnu-cxx03.tar.gz"
[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "deac959a1d14801cfd405826b3d84a723b962899"
libc = "glibc"
os = "linux"

    [[scopehal.download]]
    sha256 = "a2056986be9336166b28500ff632e70748c2cec011cb42b84a84de48a585f1ae"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.i686-linux-gnu-cxx11.tar.gz"
[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "246784cb1338b3b1cacb953dbcd01dd931f980b3"
os = "windows"

    [[scopehal.download]]
    sha256 = "aa4d12e94f8334690a85422d463a89b8d76cd098796be0a11b59bfc8a2f613e9"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dcdec46d97964373f819f53d4125f01274d9728c"
os = "windows"

    [[scopehal.download]]
    sha256 = "dc82e8e3bfe4d3c30e4b821b4df1b3cd069865deda23e5d4d231a471e4adc3c2"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eca05d31c3d0cca2e4c74448595e45509fc70b71"
libc = "glibc"
os = "linux"

    [[scopehal.download]]
    sha256 = "2ac3eaa9e3ae2405863f1e517a555db84476c331022489af8bffc26938813a1b"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a045c02ae8c1d8c7218c90b71dda690a21a0b1e"
libc = "glibc"
os = "linux"

    [[scopehal.download]]
    sha256 = "177b34b5ffbb55be346b8a43610715ad0e1b9be80b4e1d9a3c77571d4fd0b851"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "484e0e8fd9bc78c71aa68209628c8f8dcb2c4fe9"
libc = "musl"
os = "linux"

    [[scopehal.download]]
    sha256 = "8df06ee829d2d47b165dc8ba0d57ddb1f7f6c726c5a9d0f1be82eb017bf560bc"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "733580ed8651be092addef05c9b4c8c018032f1d"
libc = "musl"
os = "linux"

    [[scopehal.download]]
    sha256 = "4e04e169dfcf850d4bf3574b2b4f7bf2c04b69a7f5a05a2a9ffb82c5981aedf0"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e1dfe959e84e6a191b326452f7cef490e8dc6eb"
os = "freebsd"

    [[scopehal.download]]
    sha256 = "a47173f6bf5c814f31bba0ef4528c637807e5910c93026104a03506ec0042f9f"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.x86_64-unknown-freebsd-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91296e835744101f39957e5f0235966475f35a12"
os = "freebsd"

    [[scopehal.download]]
    sha256 = "435776a522eefb916a4a36bbc62be18e8dbe3482f469b9e601005fc6c5a9ed59"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.x86_64-unknown-freebsd-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9fbda9fcca312861427e2b181e99f3d4348f64e2"
os = "windows"

    [[scopehal.download]]
    sha256 = "3d01f24da3e2cadb8b435bf2d1d99074cb73992201ee696b67c8415d21242c71"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dc253ce3b6b186fc2f65f4f231838ef0c6c2134"
os = "windows"

    [[scopehal.download]]
    sha256 = "8e8741f8b2d6aee447806e74e3f819b79b73e7a01096c680d236fffd30a79855"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+1/scopehal.v0.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
