[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e512c924110590f035c0aed5c3268aeca7c1ef0f"
libc = "glibc"
os = "linux"

    [[scopehal.download]]
    sha256 = "e1386c555643ef4c7f676e7bdc0da493eb2784aac527a6f1d2844862a599c84f"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.i686-linux-gnu-cxx03.tar.gz"
[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4b34026b7b6ae23f86d07109c45428b6c9073da"
libc = "glibc"
os = "linux"

    [[scopehal.download]]
    sha256 = "d91ed35c58c5e8f338b43b10146fc7d09715bf179e4966faab80d52542e164be"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.i686-linux-gnu-cxx11.tar.gz"
[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d50497bcb560806666ee51f696935ab75d861cd6"
libc = "musl"
os = "linux"

    [[scopehal.download]]
    sha256 = "3cdd5a55098907627b1c560135c5392fe2704bfc75a35307c03fb68eb90ba58e"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.i686-linux-musl-cxx03.tar.gz"
[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "51803519d79922c77a883b67cd16913fec02b8ed"
libc = "musl"
os = "linux"

    [[scopehal.download]]
    sha256 = "47084919252de374bd14290f49cddb50b7e124ba0f7cf15d0bfc14798f43fe49"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.i686-linux-musl-cxx11.tar.gz"
[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7689f6a7465f7a3012d493757a5b439ad5f4a0c8"
os = "windows"

    [[scopehal.download]]
    sha256 = "cbabc00642d9d0dadb736d1275dde99e21233e53e5b805a96d5c30774197bcf0"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.i686-w64-mingw32-cxx03.tar.gz"
[[scopehal]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b04f3f8af344c1369b40796e99c16d186c3f7ed"
os = "windows"

    [[scopehal.download]]
    sha256 = "18833445a376cb01cfc8fdec8be8962394ed9ce796a880999b1d20e512cc6b4b"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.i686-w64-mingw32-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ff09ceb4ff6fa3a51e6a91362f7adabe9e0ab6ee"
os = "macos"

    [[scopehal.download]]
    sha256 = "cef671c7c2cbe9057720e98c9ddcb699b547a6da2f949baa0399a21f07ca832e"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-apple-darwin-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6c76f58bdd9cc110c41a4b4a66e295bf4acb8c1f"
os = "macos"

    [[scopehal.download]]
    sha256 = "bf5f0294de2e0cd98b5fcb1529faad25da91998325e5c49ece2030e8d603f01f"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-apple-darwin-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b0ee9b256c47b0cd0067647efd8beb7451447e57"
libc = "glibc"
os = "linux"

    [[scopehal.download]]
    sha256 = "f313849532cf2c634a27a8cd4feaf21fca45a35f89a0528884a6582145ba3651"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-linux-gnu-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d928cd2cee6405a68d7070f0aa86826ea1812b6"
libc = "glibc"
os = "linux"

    [[scopehal.download]]
    sha256 = "1b5eca2b5c042b6b4b75ffd81b6ea52c0b02edbe46b6026e9f6356596b41d24a"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-linux-gnu-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5053882eee3bc28ca557b915b0226e48389ce727"
libc = "musl"
os = "linux"

    [[scopehal.download]]
    sha256 = "c3411a619ea3bfbd5a3b5d0c4e87575b096a064e1a61aa4ebd56b1aea90c21f7"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-linux-musl-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cdea27329ee12576ebd9778f369de04f65167263"
libc = "musl"
os = "linux"

    [[scopehal.download]]
    sha256 = "a7b44133ab5a65ed9d8878e81b906a3e55c3c90512f2566f35a87bc55b533239"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-linux-musl-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "426710fd03014fe2cbf6d1304ac7d87737fbf74f"
os = "freebsd"

    [[scopehal.download]]
    sha256 = "b60b29525ebe513c6472f00e4f40735564287db78024e0419f4078521ca9f0ae"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-unknown-freebsd-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e937e3670d78ba1379f11d747756615fdf4b0f0b"
os = "freebsd"

    [[scopehal.download]]
    sha256 = "6fde65ede6b09145b9e801233724a81507f96cb219f0ca506b805b486982ffa7"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-unknown-freebsd-cxx11.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c43e23904d272fef5002175834fc036e94af8515"
os = "windows"

    [[scopehal.download]]
    sha256 = "75c2082133c36c7a887e1e554ed4b38a46f9638d53bd90b681dc691e656c2d7c"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[scopehal]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6f4cee1ded1dab06e0865f516beaaff727dd69e1"
os = "windows"

    [[scopehal.download]]
    sha256 = "cccf924f18f65e8e8c9927b263d5357286cf245f57622ae7071ffdaabfd710ce"
    url = "https://github.com/JuliaBinaryWrappers/scopehal_jll.jl/releases/download/scopehal-v0.1.0+0/scopehal.v0.1.0.x86_64-w64-mingw32-cxx11.tar.gz"
