# Autogenerated wrapper script for scopehal_jll for i686-w64-mingw32-cxx03
export scopehal, scopehalwrapper

using yaml_cpp_jll
using ffts_jll
using CompilerSupportLibraries_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("scopehal")
JLLWrappers.@declare_library_product(scopehal, "libscopehal.dll")
JLLWrappers.@declare_library_product(scopehalwrapper, "libscopehalwrapper.dll")
function __init__()
    JLLWrappers.@generate_init_header(yaml_cpp_jll, ffts_jll, CompilerSupportLibraries_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        scopehal,
        "bin\\libscopehal.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        scopehalwrapper,
        "bin\\libscopehalwrapper.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
