# Autogenerated wrapper script for scopehal_jll for x86_64-linux-musl-cxx03
export scopehal, scopehalwrapper

using yaml_cpp_jll
using ffts_jll
using CompilerSupportLibraries_jll
using libcxxwrap_julia_jll
JLLWrappers.@generate_wrapper_header("scopehal")
JLLWrappers.@declare_library_product(scopehal, "libscopehal.so")
JLLWrappers.@declare_library_product(scopehalwrapper, "libscopehalwrapper.so")
function __init__()
    JLLWrappers.@generate_init_header(yaml_cpp_jll, ffts_jll, CompilerSupportLibraries_jll, libcxxwrap_julia_jll)
    JLLWrappers.@init_library_product(
        scopehal,
        "lib/libscopehal.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        scopehalwrapper,
        "lib/libscopehalwrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
